package com.cmoncrieffe.satstoryelement.event;

import com.cmoncrieffe.satstoryelement.dice.DieRoller;
import com.cmoncrieffe.satstoryelement.dice.DieSize;

import java.util.Arrays;
import java.util.List;

public class UrbanEvent {
    private final List<String> events = Arrays.asList(
            "Wedding",
            "Wedding",
            "Name-giving day celebrations",
            "Name-giving day celebrations",
            "Public holiday",
            "Public holiday",
            "Procession",
            "Procession",
            "Harvest Festival",
            "Harvest Festival",
            "Festival celebrating a god",
            "Festival celebrating a god",
            "Celebration of a hero’s return",
            "Celebration of a hero’s return",
            "Market day",
            "Market day",
            "Religious rally",
            "Religious rally",
            "Official proclamation",
            "Official proclamation",
            "Amnesty",
            "Amnesty",
            "Sudden storm / gale force winds",
            "Sudden storm / gale force winds",
            "Election / Change of civic leader",
            "Election / Change of civic leader",
            "Yearly local festival",
            "Yearly local festival",
            "Assassination",
            "Assassination",
            "Performance of a play",
            "Performance of a play",
            "Musical concert",
            "Musical concert",
            "Buskers performance",
            "Buskers performance",
            "Orator / storyteller",
            "Orator / storyteller",
            "Alefest",
            "Alefest",
            "Warrior exhibition",
            "Warrior exhibition",
            "Procession of royals",
            "Procession of royals",
            "Museum exhibition",
            "Museum exhibition",
            "New building being opened",
            "New building being opened",
            "Large army passing through town",
            "Large army passing through town",
            "Gridlocked traffic",
            "Gridlocked traffic",
            "Monster invasion!",
            "Monster invasion!",
            "Conference of Wizards",
            "Conference of Wizards",
            "Graduation ceremony",
            "Graduation ceremony",
            "Graduation ceremony",
            "Traffic accident",
            "Traffic accident",
            "Freakish weather event",
            "Freakish weather event",
            "Fire in Building",
            "Fire in Building",
            "Notable local figure assassinated",
            "Notable local figure assassinated",
            "Public duel",
            "Public duel",
            "Large scale fire",
            "Large scale fire",
            "Sinkhole opens",
            "Sinkhole opens",
            "Local army returning after recent skirmish",
            "Local army returning after recent skirmish",
            "Co-ordinated attack",
            "Co-ordinated attack",
            "Protest",
            "Protest",
            "Flood",
            "Flood",
            "Martial law enforced (Reason?)",
            "Martial law enforced (Reason?)",
            "Wild magic eruption",
            "Wild magic eruption",
            "Military conscription",
            "Military conscription",
            "Revolution taking place (scale uncertain)",
            "Revolution taking place (scale uncertain)",
            "Public Execution",
            "Public Execution",
            "Storm",
            "Storm",
            "Plague",
            "Plague",
            "Earthquake",
            "Earthquake",
            "Dimensional disruption",
            "Dimensional disruption",
            "Invading force",
            "Invading force");

    public String[] getEvent() {
        return new String[] {
                ElementType.EVENT.toString(),
                events.get(DieRoller.roll0Based(DieSize.D100))
        };
    }
}
